name: uv-github-actions
run-name: ${{ github.actor }} runs uv-github-actions
on: [push]

defaults:
  run:
    shell: bash
    working-directory: ./python


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - run: uv sync

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - run: uv sync
      - run: uv run task test

  mutation-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - run: uv sync
      - run: uv run mutmut run
